### PR TITLE
fixes several issues

### LINKED ISSUE #1127: Clicking back on wallet page form yes, brings you to no page
Brief Description: When buying an item, if you click "yes" that I have a wallet, and then click back, it brings you to the page which shows all available wallets (the no option).

This should bring you back to the "yes" "no" page.

Operating System (OS and version): MAC 10.10.5 (14F1605)
OpenBazaar version (shown on `About OpenBazaar` page in menu): Version 1.0.9
Hardware: Laptop

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Always

Steps to reproduce:
1. Click BUY NOW on an item
2. Click Yes on "do you have a Bitcoin Wallet" 
3. Click Back to see "wallet page"

Observed Behavior:

Brings to wrong page

Expected Behavior:

Should bring back to original "No/yes" page

Additional info (links, images, etc go here):

### PR DESCRIPTION
**Pull request by jjeffryes**
- the back buttons skip the wallet selection
- the next button is not disabled if direct payment is the only option
- the buy modal closes when the view is navigated away from
- itemview and all subviews use the base view methods for registering
  and removing children

Closes #1127

### CODE REVIEW

File: js/views/itemVw.js [hunk 1]
```diff
@@ -170,10 +168,11 @@ module.exports = baseVw.extend({
...
         buyModel = new Backbone.Model();
     buyModel.set(this.model.attributes);
-    this.buyWizardView = new buyWizardVw({model:buyModel, parentEl: '#modalHolder', userModel: this.options.userModel});
-    this.subViews.push(this.buyWizardView);
-    this.subModels.push(buyModel);
-    $('#obContainer').addClass('overflowHidden').addClass('blur');  
+    this.buyWizardView = new buyWizardVw({model:buyModel, userModel: this.options.userModel});
+    this.registerChild(this.buyWizardView);
+    $('#modalHolder').html(this.buyWizardView.el); //add to DOM first, or accordion will have zero width when initialized
+    this.buyWizardView.render().el;
```
Comment (rmisio) [inline js/views/itemVw.js]: I think there's an errant trailing 'el' here.

File: js/views/itemVw.js [hunk 2]
```diff
@@ -170,10 +168,11 @@ module.exports = baseVw.extend({
...
+    $('#obContainer').addClass('overflowHidden').addClass('blur');
```
Comment (rmisio) [inline js/views/itemVw.js]: I know that you didn't introduce this line, but if you're in there, the classes here can be combined into one addClass call.

File: js/views/userPageVw.js [hunk 3]
```diff
@@ -1546,22 +1542,7 @@ module.exports = baseVw.extend({
   },
 
   close: function(){
```
Comment (rmisio) [inline js/views/userPageVw.js]: I think it would be safer to make this method called `remove` and then if we want to offer a `close` method, we could add in a close method that calls remove, e.g:

```
close: function() {
  this.remove();
}
```

That way, in case someone removes this view (by calling remove()), the remove functionality (colorbox close, etc...) is still called. The way it is now, they would always have to call close.

File: js/views/buyWizardVw.js [hunk 4]
```diff
@@ -165,14 +162,12 @@ module.exports = Backbone.View.extend({
     loadTemplate('./js/templates/buyWizard.html', function(loadedTemplate) {
       self.$el.html(loadedTemplate(self.model.toJSON()));
 
-      //append the view to the passed in parent
-      self.parentEl.append(self.$el);
-
       //add subviews
       self.buyDetailsView = new buyDetailsVw({model: self.model});
```
Comment (rmisio) [inline js/views/buyWizardVw.js:167]: Any view that you are creating in render should be removed first if it exists, e.g:
`self.buyDetailsView && self.buyDetailsView.remove()`

The base view will only remove children when the view is removed, but if you're re-rendering multiple times in the views lifecycle, you'll be queueing up child views.
