### PR TITLE
multiple tweaks

### LINKED ISSUE #1689: Discover page elements keep language
language change2

To reproduce: Change language on settings, and return to Discover page. Elements keep previous language.

OB 1.1.6

### LINKED ISSUE #1700: Minus 1 notifications
screen shot 2016-06-16 at 00 18 57

Not sure how this happened... was chatting in the contract discussion.

### PR DESCRIPTION
**Pull request by rmisio**
Achtung! This branch contains the unify-modals branch merged in because it depends on it. That is why the diff report for this guy looks so bloated. Once unify-modals is merged in, the diff report will be much more compact.
- closes #1689 
- fixes issue where the Settings page Reset buttons didn't appear to be working because they resulted in a cached page being loaded.
- adjusted functionality so discover searches do not uniformly ignore cache, rather if you attempt to navigate to a page you are already on, the app will "hard" refresh (i.e. delete the cache for that page and refresh with an uncached page).
- closes #1700

### CODE REVIEW

**Comment by jjeffryes** [comment]
@rmisio can you merge with master so the diffs unique to this branch are more clear? For some reason GitHub thinks it's still making all the changes from the modal branch.

**Comment by rmisio** [comment]
@jjeffryes done.

File: js/start.js [hunk 1]
```diff
@@ -444,7 +457,40 @@ var loadProfile = function(landingRoute, onboarded) {
...
+                  restartWarning.close();
+                }).on('click-restart-now', () => {
+                  location.reload();
+                }).render().open();
+              });
+
+              // If navigating to a page you're already on, we'll hard refresh so
+              // a cached page is not served, which avoids the issue of it looking
+              // like nothing happened.
+              $(document).on('click', '[href^="#"]', (e) => {
```
Comment (jjeffryes) [inline js/start.js:486]: Would it be better to put this in the click handler at line 223, so there aren't two separate checks being done on all links?

What if going to the same page is triggered in JS instead of a click on a link?

Comment (rmisio) [inline js/start.js:486]: I put it here because this depends on the router and the router is set-up at this point. Also this is more specific because this isn't on all links, but on all links that match the selector `[href^="#"]`. I suppose I could put this code in there with a couple of `if` checks, but I guess that's a matter of personal preference and I feel more comfortable with a separate function handling this case than one giant function conditionally handling different scenarios.

As of now we're not handling the case of it being triggered by JS other than for the short-cut keys (which is also in this PR). I think, for programatic routing, we need to probably handle this on a case by case basis. There were some complications in my attempts to centralize this on some type of `route` or `hashchange` event (mainly because we have a lot of hash changes that don't result in routes, so it's hard to keep track of the true previous route).

The other option is to "hijack" all the different methods of programatic routing, but there are many of them ('Backbone.history.navigate, app.router.navigate, loadUrl, location.href = "#blah", etc...). I'm thinking we need to put some honus on the developer to understand what page they are on and what page they are routing to and what they want the effect to be. If they want a hard refresh, they call `app.router.refresh()`, otherwise they could use one of the other multitude of approaches.

Comment (jjeffryes) [inline js/start.js:486]: Sounds good to me.
