### PR TITLE
Never Show Chat from Blocked GUIDS

### LINKED ISSUE #1754: Message block feature not working.
Brief Description: user betterthencash on reddit is having an issue where after selecting to block a conversation messages are still coming through. 

Operating System : Linux mint 18
OpenBazaar version : 1.1.7

### PR DESCRIPTION
**Pull request by jjeffryes**
- completely prevents chat messages being shown from blocked GUIDs
- Closes #1754

### CODE REVIEW

File: js/views/chatVw.js [hunk 1]
```diff
@@ -338,6 +338,11 @@ module.exports = baseVw.extend({
 
     if (!msg) return;
 
+    if (this.model.isBlocked(msg.sender)){
```
Comment (rmisio) [inline js/views/chatVw.js]: Can we combine this with the 'if' above?

File: js/views/chatVw.js [hunk 2]
```diff
@@ -336,7 +336,10 @@ module.exports = baseVw.extend({
         openlyChatting = false,
         conversationMd;
 
-    if (!msg) return;
+    if (!msg || this.model.isBlocked(msg.sender)){
+      //don't do anything if the user is blocked
```
Comment (rmisio) [inline js/views/chatVw.js]: IMHO, the comment is superfluous.
