### PR TITLE
Fix menu width

### LINKED ISSUE #1441: [UI] Menu problem in French
Version 1.1.4

The long phrases breaks the shape of the menu:

And generates an overflow:

### PR DESCRIPTION
**Pull request by mariodian**
Menu will stretch based on the content size. This is how OSX solves it and I suppose other OS's too.

fixes #1441

### CODE REVIEW

**Comment by jjeffryes** [comment]
This has conflicts with Master, due to the menu template being changed. Can you fix those and update the PR, @mariodian?

**Comment by mariodian** [comment]
Done

**Comment by mariodian** [comment]
Don't merge, "ported connection" menu needs to be fixed, because it uses absolute position. I'll look into it.

**Comment by mariodian** [comment]
Done. 

Had to fixed the "ported connection" menu, because it was positioned absolutely.

File: js/views/pageNavVw.js [hunk 1]
```diff
@@ -630,6 +630,8 @@ module.exports = baseVw.extend({
   },
 
   mouseenterServerSubmenuTrigger: function(e) {
+    this.serverSubmenu.css('right', this.$('.popMenu-navBarSubMenu-pageNav').outerWidth());
```
Comment (jjeffryes) [inline js/views/pageNavVw.js:633]: It would be much simpler to just change popMenu-navBarSubMenu from position: absolute to float:right.

I'll merge this and then submit a patch.

Comment (jjeffryes) [inline js/views/pageNavVw.js:633]: I'll retract that comment. Float introduces some issues with the container blocking the clicks to close the menu when you mouse off of it.

I'd rather avoid changing the right position in JavaScript, but for now I don't see a clean way to do it without reworking how the animation and hiding the menus works.
