### PR TITLE
Fix displaying moderator modal

### LINKED ISSUE #1558: Bug on "Moderator Settings" button
Brief Description: 
"Moderator Settings" button on user's page stops working after closing "Order Details" window on the right upper corner "X".

Steps to reproduce:
1. Click on any "Order Details" button on "Purchases" page.
2. Click on the right upper corner "X" to close the "Order Details" window.
3. Go to user's page.
4. Click on "..." button
5. Click on "Moderator Settings" button. It doesn't work anymore.

Hardware: OB v.1.1.5 Win 7 64 bits

Reproducible: Always

### PR DESCRIPTION
**Pull request by mariodian**
fixes #1558

### CODE REVIEW

File: js/views/moderatorSettingsVw.js [hunk 1]
```diff
@@ -40,7 +40,7 @@ module.exports = Backbone.View.extend({
       self.$el.html(loadedTemplate(self.model.toJSON()));
 
       //append the view to the passed in parent
-      self.parentEl.append(self.$el);
+      self.parentEl.show().append(self.$el);
```
Comment (jjeffryes) [inline js/views/moderatorSettingsVw.js]: The bug is happening because the modal has a fadeOut when the transaction view closes, this should fadeIn to match it, like this:

self.parentEl.append(self.$el).fadeIn(300);

Comment (mariodian) [inline js/views/moderatorSettingsVw.js]: @jjeffryes fixed
